#!/usr/bin/env bash
#
# Configure/set plugin specific variables (used by all Make helper scripts)
# Copyright 2021 Eighty/20 Results by Wicked Strong Chicks, LLC (Thomas Sjolshagen <thomas@eighty20results.com>)
#

# Local command
declare sed
sed="$(which sed)"

if [[ -z "${sed}" ]]; then
    echo "Error: The sed utility is not installed. Exiting!"
    exit 1;
fi

# Plugin specific variables (declared global)
declare -x github_url
declare -x plugin_description_text
declare -x plugin_homepage
declare -x short_description
declare -x short_name
declare -x version
declare -x remote_server
declare -x wordpress_version
declare -x branch_name
declare -x plugin_slug
declare -x codeception_update_list
declare -x search_string
declare -x update_to_check

short_description="Better Members List for Paid Memberships Pro"
plugin_description_text="Extensible, sortable & bulk action capable members listing + export to CSV tool for Paid Memberships Pro."
remote_server="${2}"
plugin_slug="${E20R_PLUGIN_NAME}"

# Remove any wordpress.org prohibited one-click update functionality as necessary
# Removes the custom one-click installer utility calls and functionality if present
read -r -a codeception_update_list <<< "yahnis-elsts"
search_string="Utilities::configureUpdateServer"
read -r -a update_to_check <<< "class-e20r-members-list.php class-utility-loader.php class-loader.php"

short_name="e20r-members-list"
plugin_homepage="https://${remote_server}/plugins/${short_name}/"
version="$(./bin/get_plugin_version.sh "${1}")"
github_url="https://github.com/eighty20results/${short_name}/"

# Plugin specific files to include/exclude and move if necessary during build
declare -x -a include=( \
	"docs" \
	"inc" \
	"languages" \
	"src" \
	"composer.json" \
	"composer.phar" \
	"CHANGELOG.md"
	"README.txt" \
	"class-e20r-members-list.php" \
	)
declare -x -a exclude=( \
	".git" \
	"docker" \
	"bin" \
	"Dockerfile" \
	"tests" \
	"Makefile" \
	"metadata.json" \
	"package.json" \
	".github" \
	".circleci" \
	"docker-compose.yml" \
	"build_readmes" \
	"build_config" \
	"build" \
	".idea" \
	"*.yml" \
	"composer.lock" \
	"docker.hub.key" \
	"vendor" \
	)
declare -x -a excluded_for_svn=(
		"trunk/.idea" \
		"trunk/.git" \
		"trunk/.circleci" \
		"trunk/.github" \
		"trunk/bin" \
		"trunk/build_env" \
		"trunk/docker" \
		"trunk/github" \
		"trunk/src/utilities/.git" \
		"trunk/src/utilities/bin" \
		"trunk/src/utilities/.gitignore" \
		"trunk/src/utilities/README.txt" \
		"trunk/src/utilities/.editorconfig" \
		"trunk/src/utilities/metadata.json" \
		"trunk/src/utilities/composer.json" \
		"trunk/test" \
		"trunk/tests" \
		"trunk/.distignore" \
		"trunk/.dockerignore" \
		"trunk/.editorconfig" \
		"trunk/.env.testing" \
		"trunk/.gitattributes" \
		"trunk/.gitignore" \
		"trunk/.phpcs.xml.dist" \
		"trunk/action.yml" \
		"trunk/codeception.dist.yml" \
		"trunk/composer.json" \
		"trunk/composer.phar" \
		"trunk/docker-compose.yml" \
		"trunk/Dockerfile" \
		"trunk/Makefile" \
		"trunk/metadata.json" \
		"trunk/package.json" \
		"trunk/patchwork.json" \
		"trunk/phpstan.dist.neon" \
		"trunk/phpunit.xml" \
		"trunk/remove_update.sh" \
		"tags/${version}" \
)
declare -x -a build=()

# Not a plugin specific variable, but expensive to populate
wordpress_version=$(wget -q -O - http://api.wordpress.org/core/stable-check/1.0/  | grep latest | awk '{ print $1 }' | sed -e 's/"//g')

# Populate the GITHUB_REF env variable if we're local
if [ -z "${GITHUB_REF}" ]; then
	echo "Setting GITHUB_REF environment variable"
	declare -x GITHUB_REF
	GITHUB_REF=$(git symbolic-ref HEAD)
fi

if [ -n "${GITHUB_REF}" ] && [ -z "${branch_name}" ]; then
	branch_name=$( awk -F/ '{ print $NF }' <<< "${GITHUB_REF}" )
fi

if [ -z "${GITHUB_WORKSPACE}" ]; then
	declare -x GITHUB_WORKSPACE
	GITHUB_WORKSPACE="${PWD}"
fi
