ARG WP_TAG
ARG APACHE_RUN_USER
ARG APACHE_RUN_GROUP
FROM ${WP_TAG}

COPY inc/wp_plugins /var/www/html/wp-content/plugins/
RUN apt-get -y update && rm -rf /var/lib/at/lists
RUN docker-php-ext-install pdo_mysql && \
	pecl install pcov && \
	docker-php-ext-enable pcov && \
	chown -R ${APACHE_RUN_USER}:${APACHE_RUN_GROUP} /var/www/html/wp-content/plugins/*
