name: 'Deploy E20R Members List to WordPress.org'
description: 'Deploy to the WordPress Plugin Repository'
author: '10up'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'blue'
