coverage:
  status:
    project:
      default:
        # basic
        target: 0
        base: auto
        paths:
          - "*.php"
          - "src/"
       # advanced settings
        branches:
          - main
        if_ci_failed: error #success, failure, error, ignore
        informational: true
        only_pulls: false
