version: "3.7"

services:
  wordpress:
    container_name: codecep-wp-${E20R_PLUGIN_NAME}
    build:
      context: .
      dockerfile: tests/_docker/Dockerfile.unittest
      args:
        WP_RELEASE: ${WP_RELEASE}
        APACHE_RUN_GROUP: ${APACHE_RUN_GROUP}
        APACHE_RUN_USER: ${APACHE_RUN_USER}
    restart: always
    ports:
      - ${WP_PORT}:80
    volumes:
      - ${LOCAL_UTILITIES_DIR}:/var/www/html/wp-content/plugins/00-e20r-utilities
      - ${LOCAL_PMPRO_DIR}:/var/www/html/wp-content/plugins/paid-memberships-pro
      - ${LOCAL_WOOCOMMERCE_DIR}:/var/www/html/wp-content/plugins/woocommerce
      - ${LOCAL_PLUGIN_DIR}:/var/www/html/wp-content/plugins/${E20R_PLUGIN_NAME}
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_SKIP_INSTALL: 'yes'
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_LOG_FILE: 1
      WORDPRESS_DEBUG_DISPLAY: 0
    depends_on:
      - database
    command:
      - /bin/sh
      - -c
      - /usr/local/bin/docker-entrypoint.sh apache2-foreground

## Configure the DATABASE instance
  database:
    image: mariadb:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: mariadb-wp-${E20R_PLUGIN_NAME}
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
    volumes:
      - ${LOCAL_PLUGIN_DIR}/tests/_data:/docker-entrypoint-initdb.d

volumes:
  wordpress:
  database:
