version: 2.1

orbs:
  php: circleci/php@1.1.0

defaults: &defaults
  working_directory: ~/repo
  parameters:
    p_version:
      default: "7.4"
      type: string
  docker:
    - image: cimg/php:<< parameters.p_version >>
      user: root

commands:
  build-test-environment:
    description: "Standard install steps for the plugin tests"
    parameters:
      p_version:
        default: "7.4"
        type: string
      composer_version:
        default: '1.28.6'
        type: string
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Install v<< parameters.composer_version >> Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/<< parameters.composer_version >>/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Pull the WordPress container image
          command: make image-pull
      - run:
          name: Verify PHP version
          command: php --version
      - php/install-composer:
          install-version: "2.0.9"
          install-dir: ./
      - php/install-packages:
          app-dir: ~/repo
          install-flags: '--no-interaction'
          vendor-dir: inc/
          with-cache: true
      - run:
          name: Remove no longer needed composer setup script
          command: sudo rm -f composer-setup.php


  build-prod-environment:
    description: "Standard install steps for the plugin tests"
    parameters:
      p_version:
        default: "7.4"
        type: string
      composer_version:
        default: '1.28.6'
        type: string
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: Pull the WordPress container image
          command: make image-pull
      - run:
          name: Install v<< parameters.composer_version >> Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/<< parameters.composer_version >>/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Verify PHP version
          command: php --version
      - php/install-composer:
          install-version: "2.0.9"
          install-dir: ./
      - php/install-packages:
          app-dir: ~/repo
          install-flags: '--no-interaction --prefer-stable'
          vendor-dir: inc/
          with-cache: true
      - run:
          name: Remove no longer needed composer setup script
          command: sudo rm -f composer-setup.php
      - setup_remote_docker:
          version: 20.10.2

  build-wordpress-container:
    description: "Configure the WordPress Stack test environment"
    parameters:
      p_version:
        default: "7.4"
        type: string
      composer_version:
        default: '1.28.6'
        type: string
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: Pull WordPress/Codeception container
          command: make image-pull
      - run:
          name: Refresh the WordPress/Codeception container
          command: make image-build
      - run:
          name: Create WordPress/Codeception container (if needed)
          command: make image-push

  build-plugin-source-container:
    description: "Container for the plugin sources"
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: Create container volume to host plugin & test sources
          command: |
            # create a dummy container which will hold a volume with config
            docker create -v /root/repo --name ${VOLUME_CONTAINER} alpine:3.4 /bin/true
            # copy a config file into this volume
            # docker cp ./* ${VOLUME_CONTAINER}:/root/repo/

jobs:
  build-container:
    <<: *defaults
    steps:
      - build-wordpress-container
      - build-test-environment

  wp-unit-test:
    <<: *defaults
    steps:
      - build-wordpress-container
      - build-test-environment
      - run:
          name: Create & start the WordPress container stack
          command: make start-stack
      - run:
          name: Load the DB if it exists
          command: make db-import
      - run:
          name: Run Unit Tests (WP & PMPro Integration tests)
          command: make wp-unit-test
      - store_artifacts:
          path: ~/tests/_output/coverage/
      - run:
          name: Stop the container stack
          command: make real-clean


  code-standards-test:
    <<: *defaults
    steps:
      - build-wordpress-container
      - build-test-environment
      - run:
          name: Run WPCS Code Standard Tests
          command: make code-standard-test
      - store_artifacts:
          path: ~/tests/_output/coverage/

  build-plugin:
    <<: *defaults
    steps:
      - build-wordpress-container
      - build-prod-environment
      - run:
          name: Create changelog source from GIT repository
          command: make gitlog
      - run:
          name: Update changelogs and set version information
          command: make new-release

workflows:
  version: 2
  run_tests:
    jobs:
      - build-container
      - code-standards-test:
          requires:
            - build-container
      - wp-unit-test:
          requires:
            - build-container
            - code-standards-test
      - build-plugin:
          requires:
            - build-container
            - code-standards-test
            - wp-unit-test
