version: 2.1

orbs:
  php: circleci/php@1.1.0

defaults: &defaults
  working_directory: ~/repo
  parameters:
    p_version:
      default: "7.4"
      type: string
  docker:
    - image: cimg/php:<< parameters.p_version >>

commands:
  build-environment:
    working_directory: ~/repo
    description: "Standard install steps for the plugin tests"
    parameters:
      p_version:
        default: "7.4"
        type: string
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
#      - php/install-php:
#          version: << parameters.p_version >>
#      - run:
#          name: Add curl and mbstring modules
#          command: |
#            sudo apt install -y php-curl php-mbstring
#            sudo docker-php-ext-enable curl
#            sudo docker-php-ext-enable mbstring
      - run:
          name: Verify PHP version
          command: php --version
      - php/install-composer:
          install-version: "2.0.9"
          install-dir: ./
      - php/install-packages:
          app-dir: ~/repo
          install-flags: '--no-interaction'
          vendor-dir: inc/
          with-cache: true
      - setup_remote_docker

jobs:
  unit-test:
    <<: *defaults
    steps:
    - build-environment
    - run:
        name: Run Unit Tests (WP & PMPro Integration tests)
        command: make wp-unit-test

  syntax-test:
    <<: *defaults
    steps:
      - build-environment
      - run:
          name: Run WPCS Code Standard Tests
          command: make code-standard-test

workflows:
  version: 2
  run_tests:
    jobs:
      - syntax-test
      - unit-test:
          requires:
            - syntax-test
