version: 2.1

orbs:
  php: circleci/php@1.1.0

defaults: &defaults
  working_directory: ~/repo
  parameters:
    p_version:
      default: "7.4"
      type: string
  docker:
    - image: cimg/php:<< parameters.p_version >>

commands:
  build-environment:
    description: "Standard install steps for the plugin tests"
    parameters:
      p_version:
        default: "7.4"
        type: string
      composer_version:
        default: '1.28.6'
        type: string
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: Install v<< parameters.composer_version >> Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/<< parameters.composer_version >>/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Verify PHP version
          command: php --version
      - php/install-composer:
          install-version: "2.0.9"
          install-dir: ./
      - php/install-packages:
          app-dir: ~/repo
          install-flags: '--no-interaction'
          vendor-dir: inc/
          with-cache: true
      - run:
          name: Remove no longer needed composer setup script
          command: sudo rm -f composer-setup.php
      - setup_remote_docker

jobs:
  wp-unit-test:
    <<: *defaults
    steps:
    - build-environment
    - run:
        name: Create & start the WordPress container stack
        command: make start-stack
    - run:
        name: Load the DB if it exists
        command: make db-import
    - run:
        name: Run Unit Tests (WP & PMPro Integration tests)
        command: make wp-unit-test
    - run:
        name: Stop the container stack
        command: make real-clean


  code-standards-test:
    <<: *defaults
    steps:
      - build-environment
      - run:
          name: Run WPCS Code Standard Tests
          command: make code-standard-test

workflows:
  version: 2
  run_tests:
    jobs:
      - code-standards-test
      - wp-unit-test:
          requires:
            - code-standards-test
