ARG WP_RELEASE=latest
ARG APACHE_RUN_GROUP=$APACHE_RUN_GROUP
ARG APACHE_RUN_USER=$APACHE_RUN_USER
FROM wordpress:$WP_RELEASE

# WordPress container is Debian based, so apt-get is a-ok.

RUN apt-get update \
	&& apt-get install -y subversion rsync git \
	&& apt-get clean -y \
	&& rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql && \
    pecl install pcov && docker-php-ext-enable pcov && \
    pecl install xdebug && docker-php-ext-enable xdebug

# RUN pecl install runkit && docker-php-ext-enable runkit

COPY tests/_docker/docker-phpstorm.ini /usr/local/etc/php/conf.d
