version: "3.2"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d:cached # Place init .sql file(s) here.

  nginx:
    volumes:
      - /tmp:/tmp:cached
      - ./:/var/www/html:cached
      - /Volumes/Development/www/clean.local/wp-content/themes/e20r-coaching:/var/www/html/wp-content/themes/e20r-coaching:cached
      - /Volumes/Development/www/clean.local/wp-content/plugins/paid-memberships-pro:/var/www/html/wp-content/plugins/paid-memberships-pro:cached
      - /Volumes/Development/www/clean.local/wp-content/plugins/00-e20r-utilities:/var/www/html/wp-content/plugins/00-e20r-utilities:cached
      - /Volumes/Development/www/clean.local/wp-content/plugins/e20r-members-list:/var/www/html/wp-content/plugins/e20r-members-list:cached
    ports:
      - target: 80 # Web server
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host

  php:
    image: wodby/wordpress:$WORDPRESS_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      DB_NAME: clean
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      ## Read instructions at https://wodby.com/stacks/wordpress/docs/local/xdebug/
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
      PHP_IDE_CONFIG: serverName=my-ide
      PHP_XDEBUG_REMOTE_LOG: /tmp/php-xdebug.log
      # PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
      PHP_XDEBUG_REMOTE_HOST: ts-laptop.local # macOS
      # PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows
    volumes:
      - /tmp:/tmp:cached
      - ./:/var/www/html:cached
      - /Volumes/Development/www/clean.local/wp-content/themes/e20r-coaching:/var/www/html/wp-content/themes/e20r-coaching:cached
      - /Volumes/Development/www/clean.local/wp-content/plugins/paid-memberships-pro:/var/www/html/wp-content/plugins/paid-memberships-pro:cached
      - /Volumes/Development/www/clean.local/wp-content/plugins/00-e20r-utilities:/var/www/html/wp-content/plugins/00-e20r-utilities:cached
      - /Volumes/Development/www/clean.local/wp-content/plugins/e20r-members-list:/var/www/html/wp-content/plugins/e20r-members-list:cached
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:development.local"

  traefik:
    image: traefik:alpine
    ports:
      - target: 8081
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./traefik:/etc

volumes:
  files:
#    - /tmp:/tmp:cached
