version: 2

on:
  schedule:
    - cron: '0 6 * * *'

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
