name: Test of "Release to wordpress.org" workflows

on:
  push:
    tags:
      - test_workflow*

jobs:
  # To push the release (sources) to the WordPress.org SVN instance for this plugin
  wordpress:
    name: Test of "Push to wordpress.org" workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Test of "WordPress Plugin Deploy" for ${{ github.ref }}
      #with:
      #  repository: git@github.com:eighty20results/Utilities.git
      #  token: ${{ secrets.UTILITIES_ACCESS }}
      #  path: class/utilities
      # uses: eighty20results/e20r-members-list@master
      uses: eighty20results/e20r-members-list
      env:
        SLUG: e20r-members-list
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB }}

