name: Test of "Release to wordpress.org" workflows

on:
  # push:
    # Deploy when a new release tag was created
  #  tags:
  #    - v*
  tags:
    - test_workflow*
  # release:
    # Only deploy when the admin creates/publishes/edits/pre-releases from GitHub
  #  types: [edited, published]

jobs:
  # To push the release (sources) to the WordPress.org SVN instance for this plugin
  wordpress:
    name: Test of "Push to wordpress.org" workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test of "WordPress Plugin Deploy"
      #with:
      #  repository: git@github.com:eighty20results/Utilities.git
      #  token: ${{ secrets.UTILITIES_ACCESS }}
      #  path: class/utilities
      uses: eighty20results/e20r-members-list@master
      env:
        SLUG: e20r-members-list
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB }}

