name: Plugin asset/readme update
on:
  push:
    paths:
    - README.txt
    - .wordpress-org/**.jpg
jobs:
  master:
    name: Update readme or .jpg
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
