name: Build WP plugin unit-test container

on:
  push:
    tags:
      - test_workflow*

jobs:
  # To push the release (sources) to the WordPress.org SVN instance for this plugin
  build-containers:
    name: Build the plugin unit-test container for ${{ github.repository }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4' ]
    steps:
      # All steps after this one will have env variable `E20R_PLUGIN_NAME` passed to them.
      - uses: actions/checkout@v2
      #        with:
      #          repository: eighty20results/${{ env.E20R_PLUGIN_NAME }}
      #          ssh_key: ${{ env.E20R_SSH_KEY }}
      ##          ref: test_workflow_updates
      #          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shivammathur/setup-php@v2
      - run: echo E20R_PLUGIN_NAME=$(echo ${{ github.repository }} | awk -F / '{print $2}') >> $GITHUB_ENV
      - run: sudo apt-get update -y && sudo apt-get install -y bc
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          tools: composer:v2, phpunit, pecl, php-cs-fixer, phpcs, phplint, phpmd, phpstan
          coverage: pcov

      - name: Pull the container from the Docker HUB
        run: ls -l && make image-pull
        env:
          E20R_PLUGIN_NAME: ${{ env.E20R_PLUGIN_NAME }}

      - name: Update the container (build if necessary)
        run: make image-build
        shell: bash
        env:
          E20R_PLUGIN_NAME: ${{ env.E20R_PLUGIN_NAME }}
